### ISSUE TITLE
Unable to Download 

### ISSUE THREAD

**Issue by mightylucasj** [natrixdev/Discord-Server-Boost-Botter#15]
So, I download the file. Unzip it. Then the 3 files in the zip, all make me use a application like word or firefox (as examples), I can not get past this step.

**Comment by natrixdev** [comment]
> So, I download the file. Unzip it. Then the 3 files in the zip, all make me use a application like word or firefox (as examples), I can not get past this step.

You just need to install python on your machine and double click on the file.

**Comment by mightylucasj** [comment]
DM me the Python stuff | (mightylucasj#6417)
