### ISSUE TITLE
natrix-booster error

### ISSUE THREAD

**Issue by Missoupro** [natrixdev/Discord-Server-Boost-Botter#2]
Hello, thank you for your sharing but we got some problemw with "natrix_booter.py", the attribut "filter" is not recognized.

Traceback (most recent call last):
File "natrix_booster.py", line 14, in
accounts = accounts.filter="https://github.com/natrixdev/Discord-Server-Boost-Botter/blob/main/config/accounts/acc.py"
AttributeError: 'str' object has no attribute 'filter'

Thank you again.

**Comment by natrixdev** [comment]
Yes, I have heard of this problem. I have not encountered it myself.
I will try to find out where it comes from and fix it as soon as possible!

Thank you for your feedback

**Comment by F8Hyper** [comment]
Yeah, im getting the same issue

**Comment by natrixdev** [comment]
Issue will be fixed in the week, thanks for your feedback.
