### ISSUE TITLE
discord invite invalid

### ISSUE THREAD

**Issue by Nipazuus** [natrixdev/Discord-Server-Boost-Botter#24]
Please leave a new invite

**Comment by natrixdev** [comment]
sure : https://discord.gg/jYhBKSFM6q

**Comment by dragonGRaf** [comment]
> sure : [discord.gg/jYhBKSFM6q](https://discord.gg/jYhBKSFM6q)

invalid again lul
make a telegram then link it there so we odnt always have to make a issue
