### ISSUE TITLE
Fingerprints error

### ISSUE THREAD

**Issue by RetrosGUIs** [natrixdev/Discord-Server-Boost-Botter#26]
fingerprints = json.load(open("fingerprints.json", encoding="utf-8"))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'fingerprints.json'

**Comment by RetrosGUIs** [comment]
fixed , nvm

**Comment by femb-y** [comment]
> fixed , nvm

how'd you fix? i used a fingerprints file from another boost bot (assuming this one is skidded) but i'm not sure if that's what i was supposed to do

**Comment by natrixdev** [comment]
fixed
